import { DataSource } from 'typeorm';
import { ProjectService } from './services/project.js';
import { ImplicitRuleService } from './services/implicitRule.js';
import { TranslationService } from './services/translation.js';
import { RepositoryService } from './services/repository.js';
import { ConfigurationService } from './services/configuration.js';
import { UserService } from './services/user.js';
import { SubscriptionService } from './services/subscription.js';
import { FileService } from './services/file.js';
import { KnowledgeBaseService } from './services/knowledgeBase.js';
import { TeamService } from './services/team.js';
import { InvitationService } from './services/invitation.js';
export declare function initializeDIContainer(dataSource: DataSource): Promise<void>;
export declare function destroyDIContainer(): Promise<void>;
export declare function clearProjects(): Promise<void>;
export declare function clearImplicitRules(): Promise<void>;
export declare function clearTranslations(): Promise<void>;
export declare function clearUsers(): Promise<void>;
export declare function clearSubscriptions(): Promise<void>;
export declare function clearRepositories(): Promise<void>;
export declare function clearConfigurations(): Promise<void>;
export declare function clearKnowledgeBases(): Promise<void>;
export declare function clearTeams(): Promise<void>;
export declare function clearInvitations(): Promise<void>;
export declare function clearFiles(): Promise<void>;
export declare function clearAll(): Promise<void>;
export declare function getProjectService(): ProjectService;
export declare function getImplicitRuleService(): ImplicitRuleService;
export declare function getTranslationService(): TranslationService;
export declare function getUserService(): UserService;
export declare function getTeamService(): TeamService;
export declare function getSubscriptionService(): SubscriptionService;
export declare function getRepositoryService(): RepositoryService;
export declare function getConfigurationService(): ConfigurationService;
export declare function getFilesService(): FileService;
export declare function getKnowledgeBaseService(): KnowledgeBaseService;
export declare function getInvitationService(): InvitationService;
